version: '3.7'
services:
  mysqldb_employee:
    image: mysql:8
    restart: always
    container_name: mysqldb_employee
    volumes:
      - employee_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=employee
      - MYSQL_USER=employee-user
      - MYSQL_PASSWORD=admin
      - TZ=Singapore
    networks:
      - employee_network
  web_employee:
    build: .
    restart: always
    container_name: web_employee
    volumes:
      - /tmp/employee/logs:/opt/app/logs
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: mysql
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb_employee:3306/employee?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: employee-user
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - mysqldb_employee
    networks:
      - employee_network
    links:
      - mysqldb_employee

volumes:
  employee_data:

networks:
  employee_network:
    driver: bridge