spring:
  application:
    name: springboot-practice
  datasource:
    url: jdbc:h2:file:./data/employee
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    hibernate:
      ddl-auto: none # !!IMPORTANT!! - set to `create` only if recreate tables, this will delete all data
    show-sql: true
  h2:
    console:
      enabled: true
logging:
  file:
    name: ./logs/springboot-practice.log
  level:
    root: info
