spring:
  profiles:
    active: mysql
  application:
    name: springboot-practice
  datasource:
    url: jdbc:h2:file:./data/employee
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create # !!IMPORTANT!! - set to `create` only if recreate tables, this will delete all data
    show-sql: true
  h2:
    console:
      enabled: true
logging:
  file:
    name: ./logs/springboot-practice.log
  level:
    root: info

app:
  jwt-secret: top-secret-change-me
  jwt-expiration-ms: 50000
