spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee?allowPublicKeyRetrieval=true&useSSL=false
    username: employee-user
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

